version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/webapps/backend/
    overwrite: true
    exclude_patterns:
      - '.env'

permissions:
  - object: /home/ubuntu/webapps/backend/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
      - directory

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate.sh
      timeout: 120
      runas: ubuntu
