
package esea.backend.neoslo;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "NeoSloWs", targetNamespace = "http://service.sso.common.branch.neo.hanwha/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NeoSloWs {


    /**
     * 
     * @param id
     * @param target
     * @param type
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://service.sso.common.branch.neo.hanwha/", className = "esea.backend.neoslo.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://service.sso.common.branch.neo.hanwha/", className = "esea.backend.neoslo.CreateResponse")
    public String create(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "target", targetNamespace = "")
        String target);

    /**
     * 
     * @param otaId
     * @param target
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.sso.common.branch.neo.hanwha/", className = "esea.backend.neoslo.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.sso.common.branch.neo.hanwha/", className = "esea.backend.neoslo.LoginResponse")
    public String login(
        @WebParam(name = "otaId", targetNamespace = "")
        String otaId,
        @WebParam(name = "target", targetNamespace = "")
        String target);

}
